services:
  db_postgres_projex:
    image: postgres
    container_name: db_challenge_projex
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - db_pg_projex:/var/lib/postgresql/data
    
    
  
  node_app_back_challenge:
    container_name: projex_back_challenge
    build: .
    ports:
      - 80:4000
    depends_on:
      - db_postgres_projex
    env_file:
      - .env
    
volumes:
  db_pg_projex:
